<?php

return [

    'TWITTER_TOKEN' => env('TWITTER_TOKEN', ''),
    'TWITTER_TOKEN_SECRET' => env('TWITTER_TOKEN_SECRET', ''),
    'TWITTTER_CONSUMER_KEY' => env('TWITTTER_CONSUMER_KEY', ''),
    'TWITTER_COMSUPER_SECRET' => env('TWITTER_COMSUPER_SECRET', ''),
    'TWITTER_DEFAULT_FETCH_COUNT' => env('TWITTER_DEFAULT_FETCH_COUNT', ''),
    'TWITTER_USER_NAME' => env('TWITTER_USER_NAME', '')
];
